# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da6b2c52b76810ae71385f3995559b2376ef93f076f3e5c4ba567262ae9ac1c5c8c0e8269b3d50143f37614894c8b775f5eaf6454c92b66b4dcecda6b631e0c0

test:
  secret_key_base: b5e7f853e3b5dc47ddf2ac788a6887e00891a581dcb2b72afbe594a90a2ca1361d833d3118a915a41efee8dfa0dacea02a6aa99632256bbc91f77dd8e7be8a59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
